default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test: &test
  <<: *default
  database: db/test.sqlite3

db1_test:
  <<: *test

db2_test:
  <<: *test

production:
  <<: *default
  database: db/production.sqlite3
